### ISSUE TITLE
what is arxivMarkdown.js for?

### ISSUE THREAD

**Issue by lijiansong** [robertsdionne/neural-network-papers#2]
This archive contains a js file named `arxivMarkdown.js`, what is this file for? automatically generate README？

**Comment by lijiansong** [comment]
automatically generate README？

**Comment by greenstick** [comment]
I'm not the author, though reading the code it appears to parse an HTML document, extracting metadata (title, author(s), etc.) and then generates a markdown citation and copies it to your computers clipboard (i.e. copy + paste). As for that it's use in this repository is, I can't say for sure, though I might guess that it's used to extract markdown references to papers from arxiv for input into README.md.

**Comment by robertsdionne** [comment]
It's a bookmarklet, just for `arxiv.org` abstract pages, that quickly generates a markdown link with title, authors, and the URL.

For instance, running the bookmarklet on the page https://arxiv.org/abs/1607.06048 generates
```markdown
[First Passage Under Restart](https://arxiv.org/abs/1607.06048 "Arnab Pal, Shlomi Reuveni")
```

**Comment by lijiansong** [comment]
@robertsdionne Nice!
